import type { Metadata } from "next";
import { ClientAuthProvider } from '@/components/ClientAuthProvider';
import { ReactQueryProvider } from '@/components/ReactQueryProvider';
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning className="antialiased">
        <ReactQueryProvider>
          <ClientAuthProvider>
            {children}
          </ClientAuthProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
